### ISSUE TITLE
comments on site prototype

### ISSUE THREAD

**Issue by gernotstarke** [gernotstarke/PDFminion#20]
* prefer to have the source in markdown, not "index.html"
* logo only once, on splash (aka: remove in nav-header)
* how to add additional pages (e.g. architecture documentation?)

**Comment by Per-Starke** [comment]
@gernotstarke 

To use Markdown, files need to end in .md, then both html and markdown works in these files.

To create additional pages, it works just as usual. Create a new file in /pages, and front matter, maybe add to navigation (without the # in front of the link as for the one-page links), done. Easy as that :)
